export const de = {
  Actions: "Aktion",
  "Add contact": "Kontakt hinzufügen",
  Adress: "Adresse",
  "Back to list": "Zurück zur Liste",
  "Basic Data": "Basisdaten",
  Cancel: "Abbrechen",
  "Categories / Origins": "Kategorien",
  City: "Stadt",
  Close: "Schließen",
  "Contact Person": "Ansprechpartner",
  "Contact selection": "Kontaktauswahl",
  "Contact type": "Kontakttyp",
  Country: "Land",
  Delete: "Löschen",
  "Delete object": "Objekt löschen",
  Description: "Beschreibung",
  Designation: "Bezeichnung",
  Duplicate: "Duplikat",
  "E-Mail": "E-Mail",
  "Edit object": "Objekt bearbeiten",
  "Event Data": "Event Daten",
  "Event Objects": "Event Objekte",
  Fax: "Fax",
  "First name": "Vorname",
  Height: "Höhe",
  "Last name": "Nachname",
  Length: "Länge",
  Logo: "Logo",
  "Main image": "Hauptbild",
  Media: "Medien",
  Mobile: "Mobil",
  "No valid contact ID selected. Redirect to contact list.":
    "Keine gültige Kontakt ID angegeben. Weiterleitung zur Kontaktliste",
  "No valid object ID selected. Redirect to object list.":
    "Keine gültige Objekt ID angegeben. Weiterleitung zur Objektliste",
  Notes: "Notizen",
  "Numbers and Contact Information": "Nummern und Kontakinformationen",
  OK: "OK",
  "Object selection": "Objektauswahl",
  Organisation: "Organisation",
  Origin: "Herkunft",
  Person: "Person",
  Phone: "Telefon",
  Photo: "Foto",
  Reload: "Neu laden",
  Responsibility: "Zuständigkeit",
  Salutation: "Anrede",
  Save: "Speichern",
  Search: "Suche",
  "Select image from media library": "Bild aus Medienbibliothek übernehmen",
  "Social Media & Online Presence": "Social Media & Online Präsenz",
  State: "Bundesland",
  "Tent / Hut": "Zelt / Hütte",
  Title: "Titel",
  Type: "Typ",
  Width: "Breite",
  "Width x Length": "Breite x Höhe",
  ZIP: "PLZ",
  or: "oder",
  other: "andere",
};
export const en = {
  Actions: "Actions",
  "Add contact": "Add contact",
  Adress: "Adress",
  "Back to list": "Back to list",
  "Basic Data": "Basic Data",
  Cancel: "Cancel",
  "Categories / Origins": "Categories / Origins",
  City: "City",
  Close: "Close",
  "Contact Person": "Contact Person",
  "Contact selection": "Contact selection",
  "Contact type": "Contact type",
  Country: "Country",
  Delete: "Delete",
  "Delete object": "Delete object",
  Description: "Description",
  Designation: "Designation",
  Duplicate: "Duplicate",
  "E-Mail": "E-Mail",
  "Edit object": "Edit object",
  "Event Data": "Event Data",
  "Event Objects": "Event Objects",
  Fax: "Fax",
  "First name": "First name",
  Height: "Height",
  "Last name": "Last name",
  Length: "Length",
  Logo: "Logo",
  "Main image": "Main image",
  Media: "Media",
  Mobile: "Mobile",
  "No valid contact ID selected. Redirect to contact list.":
    "No valid contact ID selected. Redirect to contact list.",
  "No valid object ID selected. Redirect to object list.":
    "No valid object ID selected. Redirect to object list.",
  Notes: "Notes",
  "Numbers and Contact Information": "Numbers and Contact Information",
  OK: "OK",
  "Object selection": "Object selection",
  Organisation: "Organisation",
  Origin: "Origin",
  Person: "Person",
  Phone: "Phone",
  Photo: "Photo",
  Reload: "Reload",
  Responsibility: "Responsibility",
  Salutation: "Salutation",
  Save: "Save",
  Search: "Search",
  "Select image from media library": "Select image from media library",
  "Social Media & Online Presence": "Social Media & Online Presence",
  State: "State",
  "Tent / Hut": "Tent / Hut",
  Title: "Title",
  Type: "Type",
  Width: "Width",
  "Width x Length": "Width x Length",
  ZIP: "ZIP",
  or: "or",
  other: "other",
};

export default { de, en };
